micronaut:
  application:
    name: envEndpointIssue
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'pleJwtCookieLoginHandleraseChangeThisSecretForANewOne'

scrt-tkn: very-secret-token
